### Question 1: [Index] S&P 500 Stocks Added to the Index
**Which year had the highest number of additions?**

Using the list of **S&P 500 companies** from Wikipedia's S&P 500 companies https://en.wikipedia.org/wiki/List_of_S%26P_500_companies page, download the data including the year each company was added to the index.

* Create a DataFrame with company tickers, names, and the year they were added.
* Extract the year from the addition date and calculate the number of stocks added each year.
* Which year had the highest number of additions (1957 doesn't count, as it was the year when the S&P 500 index was founded)? Write down this year as your answer (the most recent one, if you have several records).

Context:

"Following the announcement, all four new entrants saw their stock prices rise in extended trading on Friday" - recent examples of S&P 500 additions include DASH, WSM, EXE, TKO in 2025 (**Nasdaq article**) https://www.nasdaq.com/articles/sp-500-reshuffle-dash-tko-expe-wsm-join-worth-buying.

Additional: How many current S&P 500 stocks have been in the index for more than 20 years? When stocks are added to the S&P 500, they usually experience a price bump as investors and index funds buy shares following the announcement.

- downloading the data

In [2]:
import pandas as pd

In [ ]:
# Wikipedia Link of S&P 500 Companies
url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"

# read the tables with pandas
tables = pd.read_html(url)

# S&P 500 table list
sp500_table = tables[0]

# Save to CSV
sp500_table.to_csv("sp500_companies.csv", index=False)
print("S&P 500 data saved to sp500_companies.csv")

S&P 500 data saved to sp500_companies.csv

- Create a DataFrame with company tickers, names, and the year they were added.

In [ ]:
sp500_df = pd.read_csv("/content/sp500_companies.csv")
sp500_df

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
...,...,...,...,...,...,...,...,...
498,XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components,"White Plains, New York",2011-11-01,1524472,2011
499,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
500,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
501,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [ ]:
# Get full info of the dataframe
sp500_table.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Symbol                 503 non-null    object
 1   Security               503 non-null    object
 2   GICS Sector            503 non-null    object
 3   GICS Sub-Industry      503 non-null    object
 4   Headquarters Location  503 non-null    object
 5   Date added             503 non-null    object
 6   CIK                    503 non-null    int64
 7   Founded                503 non-null    object
dtypes: int64(1), object(7)
memory usage: 31.6+ KB

- Extract the year from the addition date and calculate the number of stocks added each year

In [ ]:
# Convert the Date added Column to datetime format
sp500_df['Date added'] = pd.to_datetime(sp500_df['Date added'])

# Extract the year from the Date added column
sp500_df['Year added'] = sp500_df['Date added'].dt.year

# view the new dataframe with new column 'Year added'
sp500_df

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded,Year added
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902,1957
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916,2017
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888,1957
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888),2012
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989,2011
...,...,...,...,...,...,...,...,...,...
498,XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components,"White Plains, New York",2011-11-01,1524472,2011,2011
499,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997,1997
500,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969,2019
501,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927,2001
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952,2013

In [ ]:
# Group by 'Year added' and count number of entries
stocks_per_year = sp500_df.groupby('Year added').size().reset_index(name='Number of Stocks Added each year')
(stocks_per_year)

    Year added  Number of Stocks Added each year
0         1957                                53
1         1964                                 1
2         1965                                 2
3         1969                                 2
4         1970                                 2
5         1972                                 2
6         1973                                 2
7         1974                                 1
8         1975                                 2
9         1976                                11
10        1978                                 1
11        1979                                 2
12        1980                                 3
13        1981                                 3
14        1982                                 5
15        1983                                 3
16        1984                                 5
17        1985                                 7
18        1986                                 3
19        1987                                 2
20        1988                                 4
21        1989                                 5
22        1991                                 1
23        1992                                 3
24        1993                                 3
25        1994                                 7
26        1995                                 7
27        1996                                 2
28        1997                                14
29        1998                                11
30        1999                                 9
31        2000                                 9
32        2001                                 8
33        2002                                13
34        2003                                 5
35        2004                                 6
36        2005                                 7
37        2006                                10
38        2007                                12
39        2008                                17
40        2009                                12
41        2010                                 9
42        2011                                10
43        2012                                14
44        2013                                10
45        2014                                 8
46        2015                                14
47        2016                                23
48        2017                                23
49        2018                                14
50        2019                                22
51        2020                                12
52        2021                                15
53        2022                                16
54        2023                                15
55        2024                                16
56        2025                                 5

- Which year had the highest number of additions (1957 doesn't count, as it was the year when the S&P 500 index was founded)? Write down this year as your answer (the most recent one, if you have several records).

In [ ]:
stocks_per_year.sort_values(by='Number of Stocks Added each year', ascending=False)

    Year added  Number of Stocks Added each year
0         1957                                53
47        2016                                23
48        2017                                23
50        2019                                22
39        2008                                17
55        2024                                16
53        2022                                16
54        2023                                15
52        2021                                15
46        2015                                14
49        2018                                14
28        1997                                14
43        2012                                14
33        2002                                13
38        2007                                12
51        2020                                12
40        2009                                12
9         1976                                11
29        1998                                11
37        2006                                10
44        2013                                10
42        2011                                10
31        2000                                 9
41        2010                                 9
30        1999                                 9
45        2014                                 8
32        2001                                 8
26        1995                                 7
25        1994                                 7
17        1985                                 7
36        2005                                 7
35        2004                                 6
14        1982                                 5
16        1984                                 5
34        2003                                 5
56        2025                                 5
21        1989                                 5
20        1988                                 4
12        1980                                 3
13        1981                                 3
24        1993                                 3
18        1986                                 3
15        1983                                 3
23        1992                                 3
5         1972                                 2
2         1965                                 2
3         1969                                 2
4         1970                                 2
19        1987                                 2
8         1975                                 2
6         1973                                 2
11        1979                                 2
27        1996                                 2
22        1991                                 1
10        1978                                 1
1         1964                                 1
7         1974                                 1

* **Answer: recent year with highest number of Stocks added = 2017**

- How many current S&P 500 stocks have been in the index for more than 20 years?

In [ ]:
# check dtype of 'Year added' as integer
sp500_df['Year added'].dtypes

dtype('int32')

In [ ]:
# Filter for added Stocks before 2005
sp500_filter = sp500_df[sp500_df['Year added'] <= 2005]

print(f'Current S&P 500 stocks for more than 20 years: {len(sp500_filter)}')

Current S&P 500 stocks for more than 20 years: 226

### Question 2. [Macro] Indexes YTD (as of 1 May 2025)
**How many indexes (out of 10) have better year-to-date returns than the US (S&P 500) as of May 1, 2025?**

Using Yahoo Finance World Indices data, compare the year-to-date (YTD) performance (1 January-1 May 2025) of major stock market indexes for the following countries:

* United States - S&P 500 (^GSPC)
* China - Shanghai Composite (000001.SS)
* Hong Kong - HANG SENG INDEX (^HSI)
* Australia - S&P/ASX 200 (^AXJO)
* India - Nifty 50 (^NSEI)
* Canada - S&P/TSX Composite (^GSPTSE)
* Germany - DAX (^GDAXI)
* United Kingdom - FTSE 100 (^FTSE)
* Japan - Nikkei 225 (^N225)
* Mexico - IPC Mexico (^MXX)
* Brazil - Ibovespa (^BVSP)

**Hint**: use ```start_date='2025-01-01' and end_date='2025-05-01'``` when downloading daily data in yfinance

Context:

Global Valuations: Who's Cheap, Who's Not? [https://simplywall.st/article/beyond-the-us-global-markets-after-yet-another-tariff-update] article suggests "Other regions may be growing faster than the US and you need to diversify."

Reference: Yahoo Finance World Indices - https://finance.yahoo.com/world-indices/

Additional: How many of these indexes have better returns than the S&P 500 over 3, 5, and 10 year periods? Do you see the same trend? Note: For simplicity, ignore currency conversion effects.

In [ ]:
#!pip install yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.11/dist-packages (0.2.61)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.11/dist-packages (from yfinance) (2.0.2)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.11/dist-packages (from yfinance) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.11/dist-packages (from yfinance) (0.0.11)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from yfinance) (4.3.8)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.11/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.11/dist-packages (from yfinance) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.11/dist-packages (from yfinance) (3.18.1)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.11/dist-packages (from yfinance) (4.13.4)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.11/dist-packages (from yfinance) (0.10.0)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.11/dist-packages (from yfinance) (5.29.4)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.11/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.13.2)
Requirement already satisfied: cffi>=1.12.0 in /usr/local/lib/python3.11/dist-packages (from curl_cffi>=0.7->yfinance) (1.17.1)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.11/dist-packages (from curl_cffi>=0.7->yfinance) (2025.4.26)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->yfinance) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->yfinance) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->yfinance) (2.4.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (2.22)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)

In [3]:
import yfinance as yf
from datetime import date
import pandas as pd

In [ ]:
#end = date.today() - pd.DateOffset(days=23)
#end

Timestamp('2025-05-01 00:00:00')

* Load the tickers for each Stock Market Index

In [ ]:
# Define start and end dates
start = date(2025, 1, 1)
end = date(2025, 5, 2)

# Print formatted output
print(f'Year = {end.year}; month= {end.month}; day={end.day}')
print(f'Period for indexes: {start} to {end}')

Year = 2025; month= 5; day=2
Period for indexes: 2025-01-01 to 2025-05-02

In [ ]:
# tickers of different stocks
tickers_obj = yf.Tickers(['^GSPC', '000001.SS', '^HSI', '^AXJO', '^NSEI', '^GSPTSE', '^GDAXI', '^FTSE', '^N225', '^MXX', '^BVSP'])
stock_indexes = tickers_obj.history(start = start, end = end, interval = "1d")
stock_indexes

[*********************100%***********************]  11 of 11 completed

Price             Close                                                    \
Ticker        000001.SS        ^AXJO     ^BVSP        ^FTSE        ^GDAXI
Date
2025-01-01          NaN          NaN       NaN          NaN           NaN
2025-01-02  3262.561035  8201.200195  120125.0  8260.099609  20024.660156
2025-01-03  3211.429932  8250.500000  118533.0  8224.000000  19906.080078
2025-01-06  3206.923096  8288.500000  120022.0  8249.700195  20216.189453
2025-01-07  3229.644043  8285.099609  121163.0  8245.299805  20340.570312
...                 ...          ...       ...          ...           ...
2025-04-25  3295.060059          NaN  134739.0  8415.299805  22242.449219
2025-04-28  3288.415039  7997.100098  135016.0  8417.299805  22271.669922
2025-04-29  3286.655029  8070.600098  135093.0  8463.500000  22425.830078
2025-04-30  3279.031006  8126.200195  135067.0  8494.900391  22496.980469
2025-05-01          NaN  8145.600098       NaN  8496.799805           NaN

Price                                                              \
Ticker            ^GSPC       ^GSPTSE          ^HSI          ^MXX
Date
2025-01-01          NaN           NaN           NaN           NaN
2025-01-02  5868.549805  24898.000000  19623.320312  49765.199219
2025-01-03  5942.470215  25073.500000  19760.269531  48957.238281
2025-01-06  5975.379883  24999.800781  19688.289062  49493.558594
2025-01-07  5909.029785  24929.900391  19447.580078  50085.500000
...                 ...           ...           ...           ...
2025-04-25  5525.209961  24710.500000  21980.740234  56720.121094
2025-04-28  5528.750000  24798.599609  21971.960938  56980.128906
2025-04-29  5560.830078  24874.500000  22008.109375  55613.429688
2025-04-30  5569.060059  24841.699219  22119.410156  56259.281250
2025-05-01  5604.140137  24795.599609           NaN           NaN

Price                     ...    Volume                                        \
Ticker             ^N225  ...     ^AXJO       ^BVSP         ^FTSE      ^GDAXI
Date                      ...
2025-01-01           NaN  ...       NaN         NaN           NaN         NaN
2025-01-02           NaN  ...  304400.0   9373600.0  4.222199e+08  52445600.0
2025-01-03           NaN  ...  329100.0   9804400.0  7.425039e+08  44372900.0
2025-01-06  39307.050781  ...   52200.0   9685600.0  7.662447e+08  70784900.0
2025-01-07  40083.300781  ...  424300.0  11116400.0  7.415068e+08  62020000.0
...                  ...  ...       ...         ...           ...         ...
2025-04-25  35705.738281  ...       NaN  13051800.0  8.027340e+08  70917400.0
2025-04-28  35839.988281  ...  769000.0  11449700.0  7.387417e+08  55883200.0
2025-04-29           NaN  ...  710800.0  12761100.0  6.559248e+08  75547100.0
2025-04-30  36045.378906  ...  889500.0  15452400.0  1.589592e+09  99189800.0
2025-05-01  36452.300781  ...  676700.0         NaN  5.275688e+08         NaN

Price                                                                          \
Ticker             ^GSPC      ^GSPTSE          ^HSI         ^MXX        ^N225
Date
2025-01-01           NaN          NaN           NaN          NaN          NaN
2025-01-02  3.621680e+09  215089400.0  4.033400e+09   87535300.0          NaN
2025-01-03  3.667340e+09  186569100.0  3.393800e+09  112782300.0          NaN
2025-01-06  4.940120e+09  239976800.0  2.465700e+09  139872100.0  137900000.0
2025-01-07  4.517330e+09  237759800.0  3.581000e+09  142173400.0  127000000.0
...                  ...          ...           ...          ...          ...
2025-04-25  4.236580e+09  214234300.0  3.025700e+09  217532100.0  134700000.0
2025-04-28  4.257880e+09  224287200.0  2.466000e+09  193000200.0  132400000.0
2025-04-29  4.747150e+09  199905200.0  3.045200e+09  240938000.0          NaN
2025-04-30  5.449490e+09  271264200.0  4.682300e+09  226957400.0  167100000.0
2025-05-01  4.935270e+09  213319000.0           NaN          NaN  131600000.0

Price
Ticker         ^NSEI
Date
2025-01-01  154900.0
2025-01-02  283200.0
2025-01-03  312300.0
2025-01-06  278100.0
2025-01-07  262300.0
...              ...
2025-04-25  387700.0
2025-04-28  320500.0
2025-04-29  357600.0
2025-04-30  424500.0
2025-05-01       NaN

[87 rows x 77 columns]

* How many indexes (out of 10) have better year-to-date returns than the US (S&P 500) as of May 1, 2025?

In [ ]:
#stock_indexes.index

In [ ]:
# Get Close for each Stock Market Index and drop all NaNs
stock_indexes = stock_indexes.Close.dropna()
stock_indexes

Ticker,000001.SS,^AXJO,^BVSP,^FTSE,^GDAXI,^GSPC,^GSPTSE,^HSI,^MXX,^N225,^NSEI
Date,,,,,,,,,,,
2025-01-06,3206.923096,8288.500000,120022.0,8249.700195,20216.189453,5975.379883,24999.800781,19688.289062,49493.558594,39307.050781,23616.050781
2025-01-07,3229.644043,8285.099609,121163.0,8245.299805,20340.570312,5909.029785,24929.900391,19447.580078,50085.500000,40083.300781,23707.900391
2025-01-08,3230.167969,8349.099609,119625.0,8251.000000,20329.939453,5918.250000,25051.699219,19279.839844,49634.261719,39981.058594,23688.949219
2025-01-10,3168.523926,8294.099609,118856.0,8248.500000,20214.789062,5827.040039,24767.699219,19064.289062,49596.699219,39190.398438,23431.500000
2025-01-14,3240.939941,8231.000000,119299.0,8201.500000,20271.330078,5842.910156,24588.599609,19219.779297,49844.000000,38474.300781,23176.050781
2025-01-15,3227.116943,8213.299805,122650.0,8301.099609,20574.679688,5949.910156,24789.300781,19286.070312,50242.839844,38444.578125,23213.199219
2025-01-16,3236.031982,8327.000000,121234.0,8391.900391,20655.390625,5937.339844,24846.199219,19522.890625,49948.148438,38572.601562,23311.800781
2025-01-17,3241.821045,8310.400391,122350.0,8505.200195,20903.390625,5996.660156,25067.900391,19584.060547,49940.890625,38451.460938,23203.199219
2025-01-21,3242.623047,8420.299805,123338.0,8548.299805,21042.000000,6049.240234,25281.599609,20106.550781,50450.261719,39027.980469,23024.650391
2025-01-22,3213.624023,8429.799805,122972.0,8545.099609,21254.269531,6086.370117,25311.500000,19778.769531,50944.578125,39646.250000,23155.349609
2025-01-23,3230.164062,8378.700195,122483.0,8565.200195,21411.529297,6118.709961,25434.099609,19700.560547,51054.910156,39958.871094,23205.349609
2025-01-24,3252.625977,8408.900391,122447.0,8502.400391,21394.929688,6101.240234,25468.500000,20066.189453,51357.308594,39931.980469,23092.199219
2025-02-05,3229.488037,8416.900391,125534.0,8623.299805,21585.929688,6061.479980,25569.800781,20597.089844,51570.191406,38831.480469,23696.300781
2025-02-06,3270.658936,8520.700195,126225.0,8727.299805,21902.419922,6083.569824,25534.500000,20891.619141,52674.789062,39066.531250,23603.349609
2025-02-07,3303.666992,8511.400391,124619.0,8700.500000,21787.000000,6025.990234,25442.900391,21133.539062,52817.750000,38787.019531,23559.949219
2025-02-10,3322.169922,8482.799805,125572.0,8767.799805,21911.740234,6066.439941,25658.900391,21521.980469,52928.121094,38801.171875,23381.599609
2025-02-12,3346.385010,8535.299805,124380.0,8807.400391,22148.029297,6051.970215,25563.099609,21857.919922,54065.718750,38963.699219,23045.250000
2025-02-13,3332.482910,8540.000000,124850.0,8764.700195,22612.019531,6115.069824,25698.500000,21814.369141,54160.109375,39461.468750,23031.400391
2025-02-14,3346.724121,8555.799805,128219.0,8732.500000,22513.419922,6114.629883,25483.199219,22620.330078,54077.941406,39149.429688,22929.250000
2025-02-18,3324.490967,8481.000000,128532.0,8766.700195,22844.500000,6129.580078,25648.800781,22976.810547,54476.738281,39270.398438,22945.300781
2025-02-19,3351.539062,8419.200195,127309.0,8712.500000,22433.630859,6144.149902,25626.199219,22944.240234,54096.511719,39164.609375,22932.900391
2025-02-20,3350.782959,8322.799805,127601.0,8663.000000,22314.650391,6117.520020,25514.099609,22576.980469,54303.929688,38678.039062,22913.150391
2025-02-21,3379.113037,8296.200195,127128.0,8659.400391,22287.560547,6013.129883,25147.000000,23477.919922,53738.750000,38776.941406,22795.900391
2025-02-25,3346.040039,8251.900391,125980.0,8668.700195,22410.269531,5955.250000,25204.000000,23034.019531,53050.328125,38237.789062,22547.550781
2025-02-27,3388.062012,8268.200195,124799.0,8756.200195,22550.890625,5861.569824,25128.199219,23718.289062,52607.609375,38256.171875,22545.050781
2025-02-28,3320.896973,8172.399902,122799.0,8809.700195,22551.429688,5954.500000,25393.500000,22941.320312,52325.730469,37155.500000,22124.699219
2025-03-05,3341.965088,8141.100098,123047.0,8755.799805,23081.029297,5842.629883,24870.800781,23594.210938,52709.398438,37418.238281,22337.300781
2025-03-06,3381.097900,8094.700195,123358.0,8682.799805,23419.480469,5738.520020,24584.000000,24369.710938,52816.429688,37704.929688,22544.699219
2025-03-07,3372.545898,7948.200195,125035.0,8679.900391,23008.939453,5770.200195,24758.800781,24231.300781,52839.628906,36887.171875,22552.500000
2025-03-10,3366.163086,7962.299805,124519.0,8600.200195,22620.949219,5614.560059,24380.699219,23783.490234,51726.878906,37028.269531,22460.300781
2025-03-11,3379.827881,7890.100098,123507.0,8496.000000,22328.769531,5572.069824,24248.199219,23782.140625,51510.679688,36793.109375,22497.900391
2025-03-12,3371.924072,7786.200195,123864.0,8541.000000,22676.410156,5599.299805,24423.300781,23600.310547,52041.011719,36819.089844,22470.500000
2025-03-13,3358.729004,7749.100098,125637.0,8542.599609,22567.140625,5521.520020,24203.199219,23462.650391,51877.121094,36790.031250,22397.199219
2025-03-18,3429.759033,7860.399902,131475.0,8705.200195,23380.699219,5614.660156,24706.099609,24740.570312,52773.320312,37845.421875,22834.300781
2025-03-19,3426.428955,7828.299805,132508.0,8706.700195,23288.060547,5675.290039,25069.199219,24771.140625,53060.761719,37751.878906,22907.599609
2025-03-21,3364.831055,7931.200195,132345.0,8646.799805,22891.679688,5667.560059,24968.500000,23689.720703,52672.421875,37677.058594,23350.400391
2025-03-24,3370.028076,7936.899902,131321.0,8638.000000,22852.660156,5767.569824,25304.099609,23905.560547,52674.839844,37608.488281,23658.349609
2025-03-25,3369.976074,7942.500000,132068.0,8663.799805,23109.789062,5776.649902,25339.500000,23344.250000,53203.261719,37780.539062,23668.650391
2025-03-26,3368.697021,7999.000000,132520.0,8689.599609,22839.029297,5712.200195,25161.099609,23483.320312,52806.890625,38027.289062,23486.849609
2025-03-27,3373.749023,7969.000000,133149.0,8666.099609,22678.740234,5693.310059,25161.099609,23578.800781,53477.738281,37799.968750,23591.949219
2025-03-28,3351.306885,7982.000000,131902.0,8658.900391,22461.519531,5580.939941,24759.199219,23426.599609,53172.968750,37120.328125,23519.349609
2025-04-01,3348.435059,7925.200195,131147.0,8634.799805,22539.980469,5633.069824,25033.300781,23206.839844,53337.898438,35624.480469,23165.699219
2025-04-02,3350.126953,7934.500000,131190.0,8608.500000,22390.839844,5670.970215,25307.199219,23202.529297,53800.929688,35725.871094,23332.349609
2025-04-03,3342.008057,7859.700195,131141.0,8474.700195,21717.390625,5396.520020,24335.800781,22849.810547,54089.281250,34735.929688,23250.099609
2025-04-07,3096.575928,7343.299805,125588.0,7702.100098,19789.619141,5062.250000,22859.500000,19828.300781,50458.320312,31136.580078,22161.599609
2025-04-08,3145.549072,7510.000000,123932.0,7910.500000,20280.259766,4982.770020,22506.900391,20127.679688,50316.589844,33012.578125,22535.849609
2025-04-09,3186.810059,7375.000000,127796.0,7679.500000,19670.880859,5456.899902,23727.000000,20264.490234,52527.671875,31714.029297,22399.150391
2025-04-11,3238.227051,7646.500000,127682.0,7964.200195,20374.099609,5363.359863,23587.800781,20914.689453,51498.898438,33585.578125,22828.550781
2025-04-15,3267.662109,7761.700195,129245.0,8249.099609,21253.699219,5396.629883,24067.900391,21466.269531,52643.039062,34267.539062,23328.550781
2025-04-16,3276.003906,7758.899902,128317.0,8275.599609,21311.019531,5275.700195,24106.800781,21056.980469,53018.570312,33920.398438,23437.199219
2025-04-22,3299.757080,7816.700195,130464.0,8328.599609,21293.529297,5287.759766,24306.000000,21562.320312,54777.839844,34220.601562,24167.250000
2025-04-23,3296.354980,7920.500000,132216.0,8403.200195,21961.970703,5375.859863,24472.699219,22072.619141,55766.578125,34868.628906,24328.949219
2025-04-24,3297.288086,7968.200195,134580.0,8407.400391,22064.509766,5484.770020,24727.500000,21909.759766,56382.000000,35039.148438,24246.699219
2025-04-28,3288.415039,7997.100098,135016.0,8417.299805,22271.669922,5528.750000,24798.599609,21971.960938,56980.128906,35839.988281,24328.500000
2025-04-30,3279.031006,8126.200195,135067.0,8494.900391,22496.980469,5569.060059,24841.699219,22119.410156,56259.281250,36045.378906,24334.199219

In [ ]:
# Calculate year-to-date returns
ytd_returns = ((stock_indexes.iloc[-1] - stock_indexes.iloc[0]) / stock_indexes.iloc[0]) * 100
ytd_returns = ytd_returns.sort_values(ascending=False)
ytd_returns

Ticker
^MXX         13.669905
^BVSP        12.535202
^HSI         12.348057
^GDAXI       11.282003
^NSEI         3.040934
^FTSE         2.972232
000001.SS     2.248508
^GSPTSE      -0.632411
^AXJO        -1.958132
^GSPC        -6.799899
^N225        -8.297931
dtype: float64

In [ ]:
# Extract S&P 500 return
sp500_return = ytd_returns['^GSPC']
sp500_return

np.float64(-6.7998994572292)

In [ ]:
# Drop S&P 500 from the comparison list
other_returns = ytd_returns.drop('^GSPC')
other_returns

Ticker
^MXX         13.669905
^BVSP        12.535202
^HSI         12.348057
^GDAXI       11.282003
^NSEI         3.040934
^FTSE         2.972232
000001.SS     2.248508
^GSPTSE      -0.632411
^AXJO        -1.958132
^N225        -8.297931
dtype: float64

In [ ]:
# Count how many indexes outperforms the S&P 500
outperforming_indexes = (other_returns > sp500_return).sum()

print(f"Number of indexes that outperformed S&P 500 YTD (as of May 1, 2025): {outperforming_indexes} out of {len(other_returns)}")

Number of indexes that outperformed S&P 500 YTD (as of May 1, 2025): 9 out of 10

#### Additional: How many of these indexes have better returns than the S&P 500 over 3, 5, and 10 year periods? Do you see the same trend? Note: For simplicity, ignore currency conversion effects.

In [ ]:
# Putting the above all in a function

def stocks_greater_than_sp500(start, end, interval: str = '1d'):
  tickers_obj = yf.Tickers(['^GSPC', '000001.SS', '^HSI', '^AXJO', '^NSEI', '^GSPTSE', '^GDAXI', '^FTSE', '^N225', '^MXX', '^BVSP'])

  stock_indexes = tickers_obj.history(start=start, end=end, interval=interval)
  stock_indexes = stock_indexes.Close.dropna()

  ytd_returns = ((stock_indexes.iloc[-1] - stock_indexes.iloc[0]) / stock_indexes.iloc[0]) * 100
  ytd_returns = ytd_returns.sort_values(ascending=False)

  sp500_return = ytd_returns['^GSPC']
  other_returns = ytd_returns.drop('^GSPC')

  outperforming_indexes = (other_returns > sp500_return).sum()
  print(f"Number of indexes that outperformed S&P 500 YTD over {n}-year period is {outperforming_indexes} out of {len(other_returns)}")
  return outperforming_indexes

-  Stocks better than S&P 500 over 3-year period

In [ ]:
n = 3
end = date(2025, 5, 2)
start_3y = date(end.year - 3, end.month, end.day)

print(f'Period for indexes: {start_3y} to {end}')

Period for indexes: 2022-05-02 to 2025-05-02

In [ ]:
sp500_3yr = stocks_greater_than_sp500(start=start_3y, end=end, interval='1d')
print(sp500_3yr)

[*********************100%***********************]  11 of 11 completed

Number of indexes that outperformed S&P 500 YTD over 3-year period is 2 out of 10
2

- Stocks better than S&P 500 over 5-year period

In [ ]:
n = 5
end = date(2025, 5, 2)
start_5y = date(end.year - 5, end.month, end.day)

print(f'Period for indexes: {start_5y} to {end}')

Period for indexes: 2020-05-02 to 2025-05-02

In [ ]:
sp500_5yr = stocks_greater_than_sp500(start=start_5y, end=end, interval='1d')
print(sp500_5yr)

[*********************100%***********************]  11 of 11 completed

Number of indexes that outperformed S&P 500 YTD over 5-year period is 2 out of 10
2

* Stocks better than S&P 500 over 10-year period

In [ ]:
n = 10
end = date(2025, 5, 2)
start_10y = date(end.year - 10, end.month, end.day)

print(f'Period for indexes: {start_10y} to {end}')

Period for indexes: 2015-05-02 to 2025-05-02

In [ ]:
sp500_10yr = stocks_greater_than_sp500(start=start_10y, end=end, interval='1d')
print(sp500_10yr)

[*********************100%***********************]  11 of 11 completed

Number of indexes that outperformed S&P 500 YTD over 10-year period is 1 out of 10
1

## Question 3. [Index] S&P 500 Market Corrections Analysis
Calculate the median duration (in days) of significant market corrections in the S&P 500 index.

For this task, define a correction as an event when a stock index goes down by more than 5% from the closest all-time high maximum.

Steps:

1. Download S&P 500 historical data (1950-present) using yfinance
2. Identify all-time high points (where price exceeds all previous prices)
3. For each pair of consecutive all-time highs, find the minimum price in between
4. Calculate drawdown percentages: (high - low) / high × 100
5. Filter for corrections with at least 5% drawdown
6. Calculate the duration in days for each correction period
7. Determine the 25th, 50th (median), and 75th percentiles for correction durations
*Context:*

* Investors often wonder about the typical length of market corrections when deciding "when to buy the dip" (Reddit discussion).
* A Wealth of Common Sense [https://awealthofcommonsense.com/2022/01/how-often-should-you-expect-a-stock-market-correction/] - How Often Should You Expect a Stock Market Correction?

*Hint (use this data to compare with your results): Here is the list of top 10 largest corrections by drawdown:*

* 2007-10-09 to 2009-03-09: 56.8% drawdown over 517 days
* 2000-03-24 to 2002-10-09: 49.1% drawdown over 929 days
* 1973-01-11 to 1974-10-03: 48.2% drawdown over 630 days
* 1968-11-29 to 1970-05-26: 36.1% drawdown over 543 days
* 2020-02-19 to 2020-03-23: 33.9% drawdown over 33 days
* 1987-08-25 to 1987-12-04: 33.5% drawdown over 101 days
* 1961-12-12 to 1962-06-26: 28.0% drawdown over 196 days
* 1980-11-28 to 1982-08-12: 27.1% drawdown over 622 days
* 2022-01-03 to 2022-10-12: 25.4% drawdown over 282 days
* 1966-02-09 to 1966-10-07: 22.2% drawdown over 240 days

In [ ]:
end = date.today()
print(f'Year = {end.year}; month= {end.month}; day={end.day}')

start = date(year=end.year-75, month=end.month, day=end.day)
print(f'Period for indexes: {start} to {end} ')

Year = 2025; month= 5; day=27
Period for indexes: 1950-05-27 to 2025-05-27

 * Step 1: download S&P 500 data from 1950 - present

In [ ]:
sp500_ticker = yf.Ticker("^GSPC")
sp500_data = sp500_ticker.history(start=start, interval="1d")
sp500_data

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1950-05-29 00:00:00-04:00,18.719999,18.719999,18.719999,18.719999,1110000,0.0,0.0
1950-05-31 00:00:00-04:00,18.780001,18.780001,18.780001,18.780001,1530000,0.0,0.0
1950-06-01 00:00:00-04:00,18.770000,18.770000,18.770000,18.770000,1580000,0.0,0.0
1950-06-02 00:00:00-04:00,18.790001,18.790001,18.790001,18.790001,1450000,0.0,0.0
1950-06-05 00:00:00-04:00,18.600000,18.600000,18.600000,18.600000,1630000,0.0,0.0
...,...,...,...,...,...,...,...
2025-05-19 00:00:00-04:00,5902.879883,5968.609863,5895.689941,5963.600098,4144010000,0.0,0.0
2025-05-20 00:00:00-04:00,5944.660156,5953.060059,5909.259766,5940.459961,4416850000,0.0,0.0
2025-05-21 00:00:00-04:00,5910.180176,5938.370117,5830.910156,5844.609863,5254250000,0.0,0.0
2025-05-22 00:00:00-04:00,5841.259766,5878.080078,5825.819824,5842.009766,5157050000,0.0,0.0
2025-05-23 00:00:00-04:00,5781.890137,5829.509766,5767.410156,5802.819824,4662820000,0.0,0.0

In [ ]:
# Another ticker download for S&P 500 data

#sp500_ticker = yf.Ticker("^SPX")
#sp500_data = sp500_ticker.history(start=start, interval="1d")
#sp500_data

* Step 2: Identify all-time high points (where price exceeds all previous prices)

In [ ]:
sp500_data['All_Time_High'] = sp500_data['Close'] > sp500_data['Close'].cummax().shift(1)
sp500_data

,Open,High,Low,Close,Volume,Dividends,Stock Splits,All_Time_High
Date,,,,,,,,
1950-05-29 00:00:00-04:00,18.719999,18.719999,18.719999,18.719999,1110000,0.0,0.0,False
1950-05-31 00:00:00-04:00,18.780001,18.780001,18.780001,18.780001,1530000,0.0,0.0,True
1950-06-01 00:00:00-04:00,18.770000,18.770000,18.770000,18.770000,1580000,0.0,0.0,False
1950-06-02 00:00:00-04:00,18.790001,18.790001,18.790001,18.790001,1450000,0.0,0.0,True
1950-06-05 00:00:00-04:00,18.600000,18.600000,18.600000,18.600000,1630000,0.0,0.0,False
...,...,...,...,...,...,...,...,...
2025-05-19 00:00:00-04:00,5902.879883,5968.609863,5895.689941,5963.600098,4144010000,0.0,0.0,False
2025-05-20 00:00:00-04:00,5944.660156,5953.060059,5909.259766,5940.459961,4416850000,0.0,0.0,False
2025-05-21 00:00:00-04:00,5910.180176,5938.370117,5830.910156,5844.609863,5254250000,0.0,0.0,False
2025-05-22 00:00:00-04:00,5841.259766,5878.080078,5825.819824,5842.009766,5157050000,0.0,0.0,False
2025-05-23 00:00:00-04:00,5781.890137,5829.509766,5767.410156,5802.819824,4662820000,0.0,0.0,False

In [ ]:
# Filter only rows where an all-time high occurred

sp500_all_time_high = sp500_data[sp500_data['All_Time_High'] == True]
sp500_all_time_high

,Open,High,Low,Close,Volume,Dividends,Stock Splits,All_Time_High
Date,,,,,,,,
1950-05-31 00:00:00-04:00,18.780001,18.780001,18.780001,18.780001,1530000,0.0,0.0,True
1950-06-02 00:00:00-04:00,18.790001,18.790001,18.790001,18.790001,1450000,0.0,0.0,True
1950-06-06 00:00:00-04:00,18.879999,18.879999,18.879999,18.879999,2250000,0.0,0.0,True
1950-06-07 00:00:00-04:00,18.930000,18.930000,18.930000,18.930000,1750000,0.0,0.0,True
1950-06-08 00:00:00-04:00,19.139999,19.139999,19.139999,19.139999,1780000,0.0,0.0,True
...,...,...,...,...,...,...,...,...
2024-12-04 00:00:00-05:00,6069.390137,6089.839844,6061.060059,6086.490234,4003390000,0.0,0.0,True
2024-12-06 00:00:00-05:00,6081.379883,6099.970215,6079.979980,6090.270020,3924830000,0.0,0.0,True
2025-01-23 00:00:00-05:00,6076.319824,6118.729980,6074.669922,6118.709961,4432250000,0.0,0.0,True
2025-02-18 00:00:00-05:00,6121.600098,6129.629883,6099.509766,6129.580078,4684980000,0.0,0.0,True
2025-02-19 00:00:00-05:00,6117.759766,6147.430176,6111.149902,6144.149902,4562330000,0.0,0.0,True

* Step 3: For each pair of consecutive all-time highs, find the minimum price in betweeen

In [ ]:
# Get all ATH dates
sp500_dates = sp500_all_time_high.index.to_list()

min_lows = []

# Loop through each pair of ATHs
for i in range(len(sp500_dates) - 1):
    start_date = sp500_dates[i]
    end_date = sp500_dates[i + 1]

    # Use the full DataFrame here!
    between_data = sp500_data.loc[start_date:end_date].iloc[1:-1]

    if not between_data.empty:
        min_close = between_data['Close'].min()
        min_close_date = between_data['Close'].idxmin()

        min_lows.append({
            'Start': start_date,
            'End': end_date,
            'min_close_date': min_close_date,
            'min_close_value': min_close
        })

# Final result
min_lows_df = pd.DataFrame(min_lows)
min_lows_df

,Start,End,min_close_date,min_close_value
0,1950-05-31 00:00:00-04:00,1950-06-02 00:00:00-04:00,1950-06-01 00:00:00-04:00,18.770000
1,1950-06-02 00:00:00-04:00,1950-06-06 00:00:00-04:00,1950-06-05 00:00:00-04:00,18.600000
2,1950-06-12 00:00:00-04:00,1950-09-22 00:00:00-04:00,1950-07-17 00:00:00-04:00,16.680000
3,1950-09-22 00:00:00-04:00,1950-09-29 00:00:00-05:00,1950-09-26 00:00:00-05:00,19.139999
4,1950-10-02 00:00:00-05:00,1950-10-04 00:00:00-05:00,1950-10-03 00:00:00-05:00,19.660000
...,...,...,...,...
639,2024-11-11 00:00:00-05:00,2024-11-26 00:00:00-05:00,2024-11-15 00:00:00-05:00,5870.620117
640,2024-11-26 00:00:00-05:00,2024-11-29 00:00:00-05:00,2024-11-27 00:00:00-05:00,5998.740234
641,2024-12-04 00:00:00-05:00,2024-12-06 00:00:00-05:00,2024-12-05 00:00:00-05:00,6075.109863
642,2024-12-06 00:00:00-05:00,2025-01-23 00:00:00-05:00,2025-01-10 00:00:00-05:00,5827.040039
643,2025-01-23 00:00:00-05:00,2025-02-18 00:00:00-05:00,2025-02-03 00:00:00-05:00,5994.569824

* Step 4: Calculate drawdown percentages: (high - low) / high × 100

In [ ]:
# Add start high (all-time high before drawdown)
min_lows_df['start_high'] = min_lows_df['Start'].apply(lambda d: sp500_data.loc[d, 'Close'])

# Calculate drawdown percentage
min_lows_df['drawdown_pct'] = ((min_lows_df['start_high'] - min_lows_df['min_close_value']) /
                               min_lows_df['start_high']) * 100

# Optional: Round for readability
min_lows_df['drawdown_pct'] = min_lows_df['drawdown_pct'].round(2)

# View result
min_lows_df[['Start', 'End', 'min_close_date', 'min_close_value', 'start_high', 'drawdown_pct']].head()

,Start,End,min_close_date,min_close_value,start_high,drawdown_pct
0,1950-05-31 00:00:00-04:00,1950-06-02 00:00:00-04:00,1950-06-01 00:00:00-04:00,18.770000,18.780001,0.05
1,1950-06-02 00:00:00-04:00,1950-06-06 00:00:00-04:00,1950-06-05 00:00:00-04:00,18.600000,18.790001,1.01
2,1950-06-12 00:00:00-04:00,1950-09-22 00:00:00-04:00,1950-07-17 00:00:00-04:00,16.680000,19.400000,14.02
3,1950-09-22 00:00:00-04:00,1950-09-29 00:00:00-05:00,1950-09-26 00:00:00-05:00,19.139999,19.440001,1.54
4,1950-10-02 00:00:00-05:00,1950-10-04 00:00:00-05:00,1950-10-03 00:00:00-05:00,19.660000,19.690001,0.15

* Step 5: Filter for corrections with at least 5% drawdown

In [ ]:
# Filter for drawdowns >= 5%
corrections_5pct = min_lows_df[min_lows_df['drawdown_pct'] >= 5]

# Display result
corrections_5pct[['Start', 'End', 'min_close_date', 'min_close_value', 'start_high', 'drawdown_pct']]

,Start,End,min_close_date,min_close_value,start_high,drawdown_pct
2,1950-06-12 00:00:00-04:00,1950-09-22 00:00:00-04:00,1950-07-17 00:00:00-04:00,16.680000,19.400000,14.02
7,1950-11-24 00:00:00-05:00,1950-12-28 00:00:00-05:00,1950-12-04 00:00:00-05:00,19.000000,20.320000,6.50
15,1951-05-03 00:00:00-04:00,1951-08-02 00:00:00-04:00,1951-06-29 00:00:00-04:00,20.959999,22.809999,8.11
21,1951-10-15 00:00:00-05:00,1952-01-03 00:00:00-05:00,1951-11-23 00:00:00-05:00,22.400000,23.850000,6.08
24,1952-01-22 00:00:00-05:00,1952-06-26 00:00:00-04:00,1952-02-20 00:00:00-05:00,23.090000,24.660000,6.37
...,...,...,...,...,...,...
570,2020-09-02 00:00:00-04:00,2020-11-13 00:00:00-05:00,2020-09-23 00:00:00-04:00,3236.919922,3580.840088,9.60
605,2021-09-02 00:00:00-04:00,2021-10-21 00:00:00-04:00,2021-10-04 00:00:00-04:00,4300.459961,4536.950195,5.21
613,2022-01-03 00:00:00-05:00,2024-01-19 00:00:00-05:00,2022-10-12 00:00:00-04:00,3577.030029,4796.560059,25.43
624,2024-03-28 00:00:00-04:00,2024-05-15 00:00:00-04:00,2024-04-19 00:00:00-04:00,4967.229980,5254.350098,5.46
631,2024-07-16 00:00:00-04:00,2024-09-19 00:00:00-04:00,2024-08-05 00:00:00-04:00,5186.330078,5667.200195,8.49

* Step 6: Calculate the duration in days for each correction period

In [ ]:
# Ensure datetime format
corrections_5pct['Start'] = pd.to_datetime(corrections_5pct['Start'])
corrections_5pct['End'] = pd.to_datetime(corrections_5pct['End'])

# Calculate duration
corrections_5pct['duration_days'] = (corrections_5pct['End'] - corrections_5pct['Start']).dt.days

# Display result
corrections_5pct[['Start', 'End', 'drawdown_pct', 'duration_days']].head()

<ipython-input-49-fb9138ab23d0>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corrections_5pct['Start'] = pd.to_datetime(corrections_5pct['Start'])
<ipython-input-49-fb9138ab23d0>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corrections_5pct['End'] = pd.to_datetime(corrections_5pct['End'])
<ipython-input-49-fb9138ab23d0>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corrections_5pct['duration_days'] = (corrections_5pct['End'] - corrections_5pct['Start']).dt.days

,Start,End,drawdown_pct,duration_days
2,1950-06-12 00:00:00-04:00,1950-09-22 00:00:00-04:00,14.02,102
7,1950-11-24 00:00:00-05:00,1950-12-28 00:00:00-05:00,6.50,34
15,1951-05-03 00:00:00-04:00,1951-08-02 00:00:00-04:00,8.11,91
21,1951-10-15 00:00:00-05:00,1952-01-03 00:00:00-05:00,6.08,80
24,1952-01-22 00:00:00-05:00,1952-06-26 00:00:00-04:00,6.37,155

* Step 7: Determine the 25th, 50th (median), and 75th percentiles for correction durations

In [ ]:
# Calculate percentiles
percentiles = corrections_5pct['duration_days'].quantile([0.25, 0.5, 0.75])

# Display result
print(percentiles)

0.25     56.0
0.50     94.0
0.75    213.5
Name: duration_days, dtype: float64

* Context

In [ ]:
top_10_drawdowns = corrections_5pct.sort_values(by='drawdown_pct', ascending=False).head(10)
top_10_drawdowns[['Start', 'End', 'drawdown_pct', 'duration_days']]

,Start,End,drawdown_pct,duration_days
441,2007-10-09 00:00:00-04:00,2013-03-28 00:00:00-04:00,56.78,1997
436,2000-03-24 00:00:00-05:00,2007-05-30 00:00:00-04:00,49.15,2622
199,1973-01-11 00:00:00-05:00,1980-07-17 00:00:00-04:00,48.20,2743
186,1968-11-29 00:00:00-05:00,1972-03-06 00:00:00-05:00,36.06,1193
567,2020-02-19 00:00:00-05:00,2020-08-18 00:00:00-04:00,33.92,180
285,1987-08-25 00:00:00-04:00,1989-07-26 00:00:00-04:00,33.51,701
124,1961-12-12 00:00:00-05:00,1963-09-03 00:00:00-04:00,27.97,629
212,1980-11-28 00:00:00-05:00,1982-11-03 00:00:00-05:00,27.11,705
613,2022-01-03 00:00:00-05:00,2024-01-19 00:00:00-05:00,25.43,746
169,1966-02-09 00:00:00-05:00,1967-05-04 00:00:00-04:00,22.18,448

* Calculate the median duration (in days) of significant market corrections in the S&P 500 index

In [ ]:
# Calculate the median duration of 5%+ corrections
median_duration = corrections_5pct['duration_days'].median()
print(f"Median duration of 5%+ corrections: {median_duration} days")

Median duration of 5%+ corrections: 94.0 days

## Question 4. [Stocks] Earnings Surprise Analysis for Amazon (AMZN)
#### Calculate the median 2-day percentage change in stock prices following positive earnings surprises days.

Steps:

1. Load earnings data from CSV (ha1_Amazon.csv) containing earnings dates, EPS estimates, and actual EPS
2. Download complete historical price data using yfinance
3. Calculate 2-day percentage changes for all historical dates: for each sequence of 3 consecutive trading days (Day 1, Day 2, Day 3), compute the return as Close_Day3 / Close_Day1 - 1. (Assume Day 2 may correspond to the earnings announcement.)
4. Identify positive earnings surprises (where "actual EPS > estimated EPS" OR "Surprise (%)>0")
5. Calculate 2-day percentage changes following positive earnings surprises
6. Compare the median 2-day percentage change for positive surprises vs. all historical dates

Context: Earnings announcements, especially when they exceed analyst expectations, can significantly impact stock prices in the short term.

Reference: Yahoo Finance earnings calendar - https://finance.yahoo.com/calendar/earnings?symbol=AMZN

Additional: Is there a correlation between the magnitude of the earnings surprise and the stock price reaction? Does the market react differently to earnings surprises during bull vs. bear markets?)

* Step 1: Load the earnings data

In [42]:
earnings_data = pd.read_csv('/content/ha1_Amazon.csv', sep=';')
earnings_data

,Symbol,Company,Earnings Date,EPS Estimate,Reported EPS,Surprise (%)
0,AMZN,Amazon.com Inc,"April 29, 2026 at 6 AM EDT",-,-,-
1,AMZN,Amazon.com Inc,"February 4, 2026 at 4 PM EST",-,-,-
2,AMZN,Amazon.com Inc,"October 29, 2025 at 6 AM EDT",-,-,-
3,AMZN,Amazon.com Inc,"July 30, 2025 at 4 PM EDT",-,-,-
4,AMZN,"Amazon.com, Inc.","May 1, 2025 at 4 PM EDT",???.36,???.59,+16.74
...,...,...,...,...,...,...
112,AMZN,"Amazon.com, Inc.","April 27, 1998 at 12 AM EDT",-,-,+13.92
113,AMZN,"Amazon.com, Inc.","January 22, 1998 at 12 AM EST",-,-,+11.41
114,AMZN,"Amazon.com, Inc.","October 27, 1997 at 12 AM EST",-,-,+13.29
115,AMZN,"Amazon.com, Inc.","July 10, 1997 at 12 AM EDT",-,-,+13.33
116,NaN,NaN,NaN,NaN,NaN,NaN

* Step 2: Download complete historical price data using yfinance

In [43]:
ticker_amzn = yf.Ticker('AMZN')
amzn_data = ticker_amzn.history(start='1997-01-01', interval='1d')
amzn_data

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1997-05-15 00:00:00-04:00,0.121875,0.125000,0.096354,0.097917,1443120000,0.0,0.0
1997-05-16 00:00:00-04:00,0.098438,0.098958,0.085417,0.086458,294000000,0.0,0.0
1997-05-19 00:00:00-04:00,0.088021,0.088542,0.081250,0.085417,122136000,0.0,0.0
1997-05-20 00:00:00-04:00,0.086458,0.087500,0.081771,0.081771,109344000,0.0,0.0
1997-05-21 00:00:00-04:00,0.081771,0.082292,0.068750,0.071354,377064000,0.0,0.0
...,...,...,...,...,...,...,...
2025-05-21 00:00:00-04:00,201.610001,203.460007,200.059998,201.119995,42460900,0.0,0.0
2025-05-22 00:00:00-04:00,201.380005,205.759995,200.160004,203.100006,38938900,0.0,0.0
2025-05-23 00:00:00-04:00,198.899994,202.369995,197.850006,200.990005,33393500,0.0,0.0
2025-05-27 00:00:00-04:00,203.089996,206.690002,202.190002,206.020004,34843100,0.0,0.0
2025-05-28 00:00:00-04:00,205.934998,207.660004,205.169998,205.678696,12855794,0.0,0.0

* Step 3: Calculate 2-day percentage changes for all historical dates: for each sequence of 3 consecutive trading days (Day 1, Day 2, Day 3), compute the return as Close_Day3 / Close_Day1 - 1. (Assume Day 2 may correspond to the earnings announcement.)

In [44]:
# Compute 2-day return using Close_Day3 / Close_Day1 - 1
amzn_data['Close_t'] = amzn_data['Close']
amzn_data['Close_t_plus_2'] = amzn_data['Close'].shift(-2)

# Calculate 2-day return (Day 3 / Day 1 - 1)
amzn_data['2_day_return'] = (amzn_data['Close_t_plus_2'] / amzn_data['Close_t']) - 1

# Drop rows where shift created NaNs
amzn_2day_returns = amzn_data.dropna(subset=['2_day_return'])
amzn_2day_returns

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Close_t,Close_t_plus_2,2_day_return
Date,,,,,,,,,,
1997-05-15 00:00:00-04:00,0.121875,0.125000,0.096354,0.097917,1443120000,0.0,0.0,0.097917,0.085417,-0.127659
1997-05-16 00:00:00-04:00,0.098438,0.098958,0.085417,0.086458,294000000,0.0,0.0,0.086458,0.081771,-0.054211
1997-05-19 00:00:00-04:00,0.088021,0.088542,0.081250,0.085417,122136000,0.0,0.0,0.085417,0.071354,-0.164639
1997-05-20 00:00:00-04:00,0.086458,0.087500,0.081771,0.081771,109344000,0.0,0.0,0.081771,0.069792,-0.146494
1997-05-21 00:00:00-04:00,0.081771,0.082292,0.068750,0.071354,377064000,0.0,0.0,0.071354,0.075000,0.051097
...,...,...,...,...,...,...,...,...,...,...
2025-05-19 00:00:00-04:00,201.649994,206.619995,201.259995,206.160004,34314800,0.0,0.0,206.160004,201.119995,-0.024447
2025-05-20 00:00:00-04:00,204.630005,205.589996,202.649994,204.070007,29470400,0.0,0.0,204.070007,203.100006,-0.004753
2025-05-21 00:00:00-04:00,201.610001,203.460007,200.059998,201.119995,42460900,0.0,0.0,201.119995,200.990005,-0.000646
2025-05-22 00:00:00-04:00,201.380005,205.759995,200.160004,203.100006,38938900,0.0,0.0,203.100006,206.020004,0.014377
2025-05-23 00:00:00-04:00,198.899994,202.369995,197.850006,200.990005,33393500,0.0,0.0,200.990005,205.678696,0.023328

Step 4: Identify positive earnings surprises (where "actual EPS > estimated EPS" OR "Surprise (%)>0")

In [45]:
# Clean and convert numeric columns
earnings_data['EPS Estimate'] = pd.to_numeric(earnings_data['EPS Estimate'], errors='coerce')
earnings_data['Reported EPS'] = pd.to_numeric(earnings_data['Reported EPS'], errors='coerce')
earnings_data['Surprise (%)'] = pd.to_numeric(earnings_data['Surprise (%)'], errors='coerce')

# Filter positive surprises
positive_surprises = earnings_data[
    (earnings_data['Reported EPS'] > earnings_data['EPS Estimate']) |
    (earnings_data['Surprise (%)'] > 0)
]

positive_surprises = positive_surprises.reset_index(drop=True).dropna()
positive_surprises

,Symbol,Company,Earnings Date,EPS Estimate,Reported EPS,Surprise (%)
4,AMZN,"Amazon.com, Inc.","April 30, 2024 at 4 PM EDT",0.83,0.98,17.91
5,AMZN,"Amazon.com, Inc.","February 1, 2024 at 4 PM EST",0.80,1.00,24.55
6,AMZN,"Amazon.com, Inc.","October 26, 2023 at 4 PM EDT",0.58,0.94,60.85
7,AMZN,"Amazon.com, Inc.","August 3, 2023 at 4 PM EDT",0.35,0.65,85.73
8,AMZN,"Amazon.com, Inc.","April 27, 2023 at 4 PM EDT",0.21,0.31,46.36
...,...,...,...,...,...,...
74,AMZN,"Amazon.com, Inc.","July 26, 2000 at 12 AM EDT",-0.02,-0.02,6.20
75,AMZN,"Amazon.com, Inc.","April 26, 2000 at 12 AM EDT",-0.02,-0.02,3.79
76,AMZN,"Amazon.com, Inc.","October 27, 1999 at 12 AM EDT",-0.01,-0.01,7.54
77,AMZN,"Amazon.com, Inc.","July 21, 1999 at 12 AM EDT",-0.01,-0.01,0.47
78,AMZN,"Amazon.com, Inc.","April 28, 1999 at 12 AM EDT",-0.01,-0.01,19.92

Step 5: Calculate 2-day percentage changes following positive earnings surprises

In [46]:
earnings_data['Earnings Date'] = pd.to_datetime(
    earnings_data['Earnings Date'].str.replace(r' [A-Z]{3}$', '', regex=True),
    format='mixed',
    errors='coerce'
).dt.tz_localize(None)

In [47]:
amzn_data.index = amzn_data.index.tz_localize(None)

In [48]:
# Filter positive surprises
positive_surprises = earnings_data[
    (earnings_data['Reported EPS'] > earnings_data['EPS Estimate']) |
    (earnings_data['Surprise (%)'] > 0)
].copy()

# Calculate 2-day returns after each positive earnings date
returns = []

for date in positive_surprises['Earnings Date']:
    # Find the nearest date in trading data (some earnings dates fall on non-trading days)
    if date not in amzn_data.index:
        date_idx = amzn_data.index.get_indexer([date], method='backfill')[0]
        date = amzn_data.index[date_idx]


    try:
        day1 = date
        day3 = amzn_data.index[amzn_data.index.get_loc(day1) + 2]  # 2 trading days later

        price_day1 = amzn_data.loc[day1]['Close']
        price_day3 = amzn_data.loc[day3]['Close']
        pct_return = (price_day3 / price_day1) - 1

        returns.append({'Earnings Date': day1, '2D Return': pct_return})
    except:
        # If day3 goes beyond available data or index error, skip
        continue

# Convert to DataFrame
returns_df = pd.DataFrame(returns)

# Merge with positive_surprises
result = pd.merge(positive_surprises, returns_df, on='Earnings Date', how='left')

result[['Earnings Date', 'EPS Estimate', 'Reported EPS', 'Surprise (%)', '2D Return']].dropna()

   Earnings Date  EPS Estimate  Reported EPS  Surprise (%)  2D Return
33    2014-04-24          0.01          0.01          0.88  -0.120332
37    2012-01-31          0.01          0.02        127.00  -0.065419
38    2011-07-26          0.02          0.02         17.28   0.045382
39    2011-01-27          0.04          0.05          3.03  -0.080293
40    2010-10-21          0.02          0.03          7.28   0.024429
41    2010-04-22          0.03          0.03          9.05  -0.019855
42    2010-01-28          0.04          0.04         17.96  -0.056812
43    2009-10-22          0.02          0.02         34.57   0.333761
44    2009-07-23          0.02          0.02          2.17  -0.102589
45    2009-04-23          0.02          0.02         32.60   0.031138
46    2009-01-29          0.02          0.03         33.20   0.223000
47    2008-10-22          0.01          0.01          9.67  -0.020604
48    2008-07-23          0.01          0.02         42.09   0.110150
49    2008-04-23          0.02          0.02          5.13  -0.001728
50    2008-01-30          0.02          0.02          0.67   0.005660
51    2007-10-23          0.01          0.01          4.74  -0.125074
52    2007-07-24          0.01          0.01         20.41   0.213141
53    2007-04-24          0.01          0.01         68.61   0.402905
54    2007-02-01          0.01          0.01          8.80  -0.039793
56    2006-04-25          0.01          0.01          2.39   0.005345
57    2006-02-02          0.01          0.02        120.86  -0.112073
58    2005-07-26          0.01          0.01         13.85   0.210387
59    2004-04-22          0.01          0.01         16.87  -0.032951
60    2004-01-27          0.01          0.01          0.21  -0.116972
64    2003-01-23          0.01          0.01         32.87  -0.000459
69    2001-10-23         -0.01         -0.01          0.25  -0.186387
70    2001-07-23         -0.01         -0.01         27.14  -0.281971
71    2001-04-24         -0.01         -0.01         17.39  -0.015944
72    2001-01-30         -0.01         -0.01          2.57  -0.141914
73    2000-10-24         -0.01         -0.01         12.95   0.247357
74    2000-07-26         -0.02         -0.02          6.20  -0.168111
75    2000-04-26         -0.02         -0.02          3.79   0.031542
76    1999-10-27         -0.01         -0.01          7.54  -0.069959
77    1999-07-21         -0.01         -0.01          0.47  -0.086697
78    1999-04-28         -0.01         -0.01         19.92  -0.110788

* Step 6: Compare the median 2-day percentage change for positive surprises vs. all historical dates

In [51]:
# Shift index by 2 days to get the 2-day forward price
price_day1 = amzn_data['Close']
price_day3 = amzn_data['Close'].shift(-2)

# Calculate returns
amzn_2d_returns = (price_day3 / price_day1) - 1

amzn_2d_returns = amzn_2d_returns.dropna()

In [53]:
# Median 2-day return after positive surprises
median_positive = result['2D Return'].median()

In [54]:
# Median 2-day return for all days
median_all = amzn_2d_returns.median()

In [55]:
print(f"Median 2-Day Return After Positive Surprises: {median_positive:.4%}")
print(f"Median 2-Day Return for All Historical Dates: {median_all:.4%}")

Median 2-Day Return After Positive Surprises: -1.5944%
Median 2-Day Return for All Historical Dates: 0.1654%